apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: webapps
  labels:
    app: postgres
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "school_management"
  SPRING_PROFILES_ACTIVE: "k8s"

  